PROJECT: "hadamRNN_quantized"
DATASET:
  NAME: CopyMemory
  SENT_LENGTH: 10
  SEQ_LENGTH: 1000
  TEST_SIZE: 2000
  TRAIN_SIZE: 512000
  VAL_SIZE: 2000
  VOCABULARY: 10
MODEL:
  ACTIVATION: $torch.nn.ReLU 
  ACTIVATION_CONFIG: null
  ACTIVATION_FINAL: null
  ACTIVATION_FINAL_CONFIG: null
  BASIC_BLOCK: 'full'
  BIAS: True
  BIAS_FINAL: True
  GIVENS: 2
  HIDDEN_SIZE: 128
  INPUT_SIZE: 10
  MANYTOMANY: True
  MULTIPARAMETERS: False
  NAME: BinadamSSM
  NUM_BITS: 4
  OUTPUT_SIZE: 9
  SEED: 712
  SINGLE_LAYER: True
  QOUTPUT: True
TRAIN:
  BATCH_SIZE: 128
  DISPLAY_EPOCH: false
  DISPLAY_EVERY: null
  LAMBDA_ORTH: 0.
  LOSS_FN: $torch.nn.CrossEntropyLoss
  LOSS_CONFIG: null
  METRICS: null
  N_EPOCHS: 10
  OPTIMIZER: $torch.optim.Adam
  OPTIMIZER_CONFIG:
    lr: 1.e-4 #0.001
  SCHEDULER: $torch.optim.lr_scheduler.StepLR
  SCHEDULER_CONFIG:
    gamma: 0.98
    step_size: 1
  TORCH_DEVICE: cuda:0
  TRACK_FLIPS: True
  USE_WANDB: False
  #COMPUTE_SV: False